# Generated by Django 5.0.3 on 2024-08-27 08:48

import datetime
import django.db.models.deletion
import month.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_electricity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cleaning', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_elevator_electricity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_elevator_maintenance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_entrance_maintenance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('number', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='building.building')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cleaning', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('elevator_electricity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('elevator_maintenance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entrance_maintenance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('for_month', month.models.MonthField(default=datetime.datetime(2024, 8, 27, 8, 48, 54, 504322, tzinfo=datetime.timezone.utc), null=True, verbose_name='Month')),
                ('is_paid', models.BooleanField(default=False)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='building.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.building')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='entrance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='building.entrance'),
        ),
    ]
