# Generated by Django 5.0.8 on 2024-09-12 07:54

import month.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(null=True)),
                ('for_month', month.models.MonthField(null=True, verbose_name='Month')),
            ],
            options={
                'ordering': ['-for_month'],
            },
        ),
    ]
