# Generated by Django 5.0.3 on 2024-08-25 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity', models.FloatField()),
                ('cleaning', models.FloatField()),
                ('el_elevator', models.FloatField()),
                ('elevator_maintenance', models.FloatField()),
                ('entrance_maintenance', models.FloatField(default=10)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.apartment')),
            ],
        ),
    ]
