# Generated by Django 5.0.3 on 2024-08-27 08:50

import datetime
import month.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_alter_apartmentbill_for_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentbill',
            name='for_month',
            field=month.models.MonthField(default=datetime.datetime(2024, 8, 27, 8, 50, 10, 545400, tzinfo=datetime.timezone.utc), null=True, verbose_name='Month'),
        ),
    ]
