# Generated by Django 5.0.3 on 2024-08-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='cleaning',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='el_elevator',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='electricity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='elevator_maintenance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='entrance_maintenance',
            field=models.IntegerField(default=10),
        ),
    ]
