# Generated by Django 5.0.3 on 2024-08-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_alter_bill_cleaning_alter_bill_el_elevator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='cleaning',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='el_elevator',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='electricity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='elevator_maintenance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='entrance_maintenance',
            field=models.FloatField(default=10),
        ),
    ]
