# Generated by Django 5.0.3 on 2024-08-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_alter_bill_cleaning_alter_bill_el_elevator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='el_elevator',
            new_name='elevator_electricity',
        ),
    ]
