# Generated by Django 5.0.8 on 2024-09-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_alter_expense_building_alter_expense_entrance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='amount',
            new_name='cost',
        ),
    ]
