# Generated by Django 5.0.3 on 2024-08-27 11:04

import month.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_alter_apartmentbill_for_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='apartmentbill',
            options={'ordering': ['apartment__number']},
        ),
        migrations.AlterModelOptions(
            name='entrance',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='apartmentbill',
            name='for_month',
            field=month.models.MonthField(null=True, verbose_name='Month'),
        ),
    ]
