# Generated by Django 5.0.3 on 2024-08-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0005_alter_apartment_options_alter_apartmentbill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentbill',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
