# Generated by Django 5.0.8 on 2024-09-12 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0007_alter_expense_maintenance_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalMaintenanceAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='maintenance_total_amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='building.totalmaintenanceamount'),
        ),
    ]
