# Generated by Django 5.0.8 on 2024-09-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0008_totalmaintenanceamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='maintenance_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
