# Generated by Django 5.0.8 on 2024-09-12 12:41

import month.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0010_alter_expense_maintenance_total_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totalmaintenanceamount',
            options={'ordering': ['-for_month']},
        ),
        migrations.AddField(
            model_name='totalmaintenanceamount',
            name='for_month',
            field=month.models.MonthField(null=True, verbose_name='Month'),
        ),
    ]
