# Generated by Django 5.0.8 on 2024-09-27 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0012_totalmaintenanceamount_building_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='building.building')),
                ('entrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='building.entrance')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
