# Generated by Django 5.0.9 on 2024-11-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0014_alter_apartment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together=set(),
        ),
    ]
